### ISSUE TITLE
scalatest 3.2.x-compatible release?

### ISSUE THREAD

**Issue by kubukoz** [IronCoreLabs/cats-scalatest#158]
Hi,

Are you going to make a release compatible with Scalatest 3.2? This dependency is blocking us from an upgrade.

If the project is no longer active, please let me know so I can plan accordingly ;)

**Comment by coltfred** [comment]
I certainly can. Sometimes I forget to cut the releases since scala steward just runs around updating. I'll do it and post here when its done.

**Comment by kubukoz** [comment]
Great, thanks :)

**Comment by coltfred** [comment]
3.1.0 is out and should be syncing. Let me know if you have any problems.

I'll fix the README shortly.
