### ISSUE TITLE
3.1.0 jar for Scala 2.12 is empty

### ISSUE THREAD

**Issue by mmatloka** [IronCoreLabs/cats-scalatest#160]
Hi,
There is something wrong with 3.1.0 jar published for Scala 2.12, there are no classes inside. mvnrepository shows 322 bytes comparing to 56KB for 2.13 https://mvnrepository.com/artifact/com.ironcorelabs/cats-scalatest_2.12/3.1.0 vs https://mvnrepository.com/artifact/com.ironcorelabs/cats-scalatest_2.13/3.1.0

**Comment by coltfred** [comment]
Hey, so sorry about this. The release is done by github actions. I'll check and see if I can reproduce.

**Comment by coltfred** [comment]
3.1.1 was released and looks good. https://repo1.maven.org/maven2/com/ironcorelabs/cats-scalatest_2.12/3.1.1/

For those curious, this is a problem with having publish in the root when you have a multi module build.

https://github.com/olafurpg/sbt-ci-release/issues/105#issuecomment-589597715 was where it was discussed. Reopen if this does not resolve your issue.
