### ISSUE TITLE
Scalatest 3.0.0

### ISSUE THREAD

**Issue by pjan** [IronCoreLabs/cats-scalatest#8]
Any chance this gets updated to work with scalatest 3.0.0?

Much appreciated!

**Comment by coltfred** [comment]
Sure thing! You can either open a PR or I can take a look at it this weekend. We probably need to support scalatest 2.x for some time so I think the plan will be to create a `cats-scalatest` `series 1.x` long running branch and bump the major version to 2.0 for supporting scalatest 3. Cats `0.7` is only a few days from release as well. Unless you explicitly need scalatest 3.x support on cats `0.6` I'll probably just wait until that's done too.

**Comment by coltfred** [comment]
@pjan I forgot to close this issue, but #12 fixed this.
