### ISSUE TITLE
Releases 3.0.1-3.0.3 are corrupted

### ISSUE THREAD

**Issue by iRevive** [IronCoreLabs/cats-scalatest#85]
Looks like releases 3.0.1-3.0.3 are corrupted, there is no source code in a jar file.  
Docs are missing as well https://www.javadoc.io/doc/com.ironcorelabs/cats-scalatest_2.12/3.0.2/index.html.

**Comment by coltfred** [comment]
3.0.1 and 3.0.2 were failed publishings, but I thought 3.0.3 was fine. I'll get an issue opened with sonatype to get them taken down and get 3.0.4 out today (hopefully). Thanks for reporting this.

**Comment by coltfred** [comment]
Apparently it's even more strange than what was posted.

2.11 JVM is good.
2.12 JVM is corrupt.
2.13 JVM is corrupt.

All ScalaJS builds are good.

**Comment by coltfred** [comment]
3.0.4 has been published. All except 2.11 should be good. If someone needs 2.11, 3.0.3 should work for them.

I've been lead to believe this happens to other projects and is a bug in SBT with cross project publishing. Let me know if you have any problems with 3.0.4

**Comment by iRevive** [comment]
3.0.4 works for me. Thanks a lot!
